sentry:
    dsn: '%env(SENTRY_DSN)%'
    listener_priorities:
        request: 101
        sub_request: 101
    options:
        excluded_exceptions:
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'