name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare containers
        run: cd api && make run && make composer-install
      - name: Run tests
        run: cd api && make tests