name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare docker-compose
        run: cd api && make run && make prepare
        env:
          APP_ENV: test
      - name: Run tests
        run: cd api && make tests