name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: cd api && docker-compose -f docker-compose.yml.dist pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - run: cd api && make run && make composer-install
      - name: Run tests
        run: cd api && make tests